package com.hearlers.gateway.shared.enums;

public enum CounselorName {
    COUNSELOR_NAME_DAHYE,
    COUNSELOR_NAME_JIHWAN,
    COUNSELOR_NAME_ELLIE,
    COUNSELOR_NAME_YOON,
    COUNSELOR_NAME_CHERRY,
    COUNSELOR_NAME_ADEN,
    COUNSELOR_NAME_HIKO,
    COUNSELOR_NAME_ARU
}
