package com.hearlers.gateway.shared.enums;

public enum ProgressStatus {
    PROGRESS_STATUS_UNSPECIFIED,
    PROGRESS_STATUS_NOT_STARTED,
    PROGRESS_STATUS_IN_PROGRESS,
    PROGRESS_STATUS_COMPLETED,
    PROGRESS_STATUS_BLOCKED
}
