rootProject.name = 'gateway'

include('api')
include('proto')
include('common')
include('domain')
include('usecase')
include('usecase:core')
include('usecase:auth-usecase')
include('usecase:counsel-usecase')
include('usecase:counselor-usecase')
include('usecase:prompt-usecase')
include('usecase:user-usecase')
include('adapter')
include('adapter:grpc')
include('adapter:jwt')
include('adapter:oauth')