kakao:
  client_id: ${KAKAO_CLIENT_ID}
  admin_key: ${KAKAO_ADMIN_KEY}
  redirect_uri: ${SERVER_URL}/v1/auth/callback/kakao
  admin_unique_ids: 3726748107, 4282012818, 4282012818, 4252068228, 3783518117, 3424055264, 3424046442

token:
  access_expiration_time: 86400 # Access token 만료 시간 : 하루
  refresh_expiration_time: 2592000 # Refresh token 만료 시간 : 한달
  jwt:
    secret: ${JWT_SECRET}

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
  use-fqn: false

grpc:
  targets:
    nest: ${GRPC_NEST_TARGET}